config/routes.rb
Rails.application.routes.draw do
    root 'restaurants#index'
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
    resources :restaurants do
        resources :reviews
    end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
    belongs_to :user
    validates :name, length: { minimum: 3 }, uniqueness: true
    has_many :reviews,
             -> { extending WithUserAssociationExtension },
             dependent: :destroy

    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

    def average_rating
        return 'N/A' if reviews.none?
        reviews.average(:rating)
    end
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :rating, inclusion: (1..5)
  # validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }
  belongs_to :user
  belongs_to :restaurant
end

app/models/user.rb
class User < ActiveRecord::Base
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable,
           :omniauthable, omniauth_providers: [:facebook]
           
    has_many :restaurants
    has_many :reviews
    has_many :reviewed_restaurants, through: :reviews, source: :restaurant

    def self.from_omniauth(auth)
        where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
            user.email = auth.info.email
            user.password = Devise.friendly_token[0, 20]
        end
    end

    def has_reviewed?(restaurant)
        reviewed_restaurants.include? restaurant
    end
end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension

   def create_with_user(attributes = {}, user)
     attributes[:user] ||= user
     create(attributes)
   end

   def create_with_user!(attributes = {}, user)
     attributes[:user] ||= user
     create!(attributes)
   end

   def build_with_user(attributes = {}, user)
     attributes[:user] ||= user
     build(attributes)
   end
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :image)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        @restaurant = Restaurant.find(params[:restaurant_id])
        @review = Review.new
    end

    def create
        @restaurant = Restaurant.find params[:restaurant_id]
        @review = @restaurant.reviews.build_with_user(review_params, current_user)
        if @review.save
            redirect_to restaurants_path
        else
            if @review.errors[:user]
                # Note: if you have correctly disabled the review button where appropriate,
                # this should never happen...
                redirect_to restaurants_path, alert: 'You have already reviewed this restaurant'
            else
                # Why would we render new again?  What else could cause an error?
                render :new
            end
        end
    end

    private

    def review_params
        params.require(:review).permit(:thoughts, :rating)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
   def star_rating(rating)
     # does the rating respond to `round`? If not, just return the rating
     return rating unless rating.respond_to?(:round)

     # if it does – i.e. if it's a valid number - then the rest of the
     # method is run
     remainder = (5 - rating.round)
     "★" * rating.round + "☆" * remainder
   end
 end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>YelpClone</title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/restaurants" style="font-weight:bold; font-size:25px;"> Yelp8</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <% if user_signed_in? %>
                        <li class="active">Welcome<strong><%= current_user.email %></strong></li>
                        <li class="active"><%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
                        <% else %>
                        <li class="active"><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
                        <li class="active"><%= link_to "Sign in", new_user_session_path, :class => 'navbar-link'  %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="notice">
            <% if notice %>
            <div class="alert alert-info fade in" role="alert">
                <a href="#" class="close" data-dismiss="alert">&times;</a>
                <ul id='notice'>
                    <li><%= notice %></li>
                </ul>
            </div>
            <% end %>
        </div>

        <div class="errors">
            <% if alert %>
            <div class="alert alert-danger fade in" role="alert">
                <a href="#" class="close" data-dismiss="alert">&times;</a>
                <ul id='errors'>
                    <li><%= alert %></li>
                </ul>
            </div>
            <% end %>
        </div>

        <div class="yield_container">
            <%= yield %>
        </div>
        <footer class="footer">
            © 2016 Yelp8 by Manuela Sabatino |
            <a href="https://github.com/ManuCiao" target="_blank">GitHub</a>
            |
            <a href="https://uk.linkedin.com/in/mnsabatino" target="_blank">LinkedIn</a>
        </footer>
    </body>
</html>

app/views/restaurants/edit.html.erb
<%= form_for @restaurant, html: {multipart: true, style:"padding:30px;"}, class:"form-horizontal" do |f| %>
  <div class="form-group">
    <%= f.label :name, class:"col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :name, class:"form-control", placeholder:"Edit the name..."%><br>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, class:"col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_area :description, class:"form-control", placeholder:"Enter a description..."%><br>
    </div>
  </div>
  <div class="form-group">
    <label for="image" class="col-sm-2 control-label">Upload Pictures</label>
    <div class="col-sm-10">
      <%= f.file_field :image, class:"form-control" %><br>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Update Restaurant", class: "btn btn-success"%>
    </div>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<div class="title">
  <span><h3>List of Restaurants</h3>
  <a href="/restaurants/new", style="float: right;", class="btn btn-success">Add Restaurants</a></span>
</div>
<% if @restaurants.any? %>
<% @restaurants.each do |restaurant| %>
<table class="table table-hover">
    <thead>
      <tr>
        <th>Restaurant Name</th>
        <th>Description</th>
        <th>Reviews</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <h4><%= link_to restaurant.name, restaurant_path(restaurant) %></h4>
          <p><%= image_tag restaurant.image.url(:thumb) %></p>
        </td>
        <td>
          <p><%= restaurant.description %></p>
          <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant), class:"btn btn-default" %>
          <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete, class:"btn btn-default" %>
        </td>
        <td>
        <% restaurant.reviews.each do |review| %>
        <p><%= review.thoughts %></p>
        <% end %>
        <h5>Average rating: <%= star_rating(restaurant.average_rating) %></h5>
        <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant), class:"btn btn-default" %>
        </td>
      </tr>
    </tbody>
  </table>
  <% end %>
  <%else %>
  <h1>No restaurants yet</h1>
  <% end %>

</div>
</div>

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
<section id="errors">
    <h2>
        <%= pluralize(@restaurant.errors.count, "error") %>
        prohibited this restaurant from being saved:
    </h2>
    <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</section>
<% end %>

<%= form_for @restaurant, html: {multipart: true, style:"padding:30px;"}, class:"form-horizontal" do |f| %>
  <div class="form-group">
    <%= f.label :name, class:"col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_field :name, class:"form-control"%><br>
    </div>
  </div>
  <div class="form-group">
    <label for="image" class="col-sm-2 control-label">Upload Pictures</label>
    <div class="col-sm-10">
      <%= f.file_field :image, class:"form-control" %><br>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Create Restaurant", class: "btn btn-success"%>
    </div>
  </div>
<% end %>

app/views/restaurants/show.html.erb
<p><%= @restaurant.name %></p>
<p><%= @restaurant.description %></p>
<p><%= @restaurant.image %></p>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review], html: {multipart: true, style:"padding:30px;"}, class:"form-horizontal" do |f| %>
  <div class="form-group">
    <%= f.label :thoughts, class:"col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.text_area :thoughts,  class:"form-control", placeholder:"Enter your thoughts..."%><br>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :rating, class:"col-sm-2 control-label"%>
    <div class="col-sm-10">
      <%= f.select :rating, (1..5) %><br><br>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Leave Review", class: "btn btn-success"%>
    </div>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>